<div class="container">
    <div class="row">
        <div class="col-md-offset-4 col-md-4">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title text-center">Add a New Post</h3>
                </div>
                <div class="panel-body">
                    <form action="<?= $this->makeUrl("post/addPost"); ?>" method="post">
                        <div class="form-group">
                            <label for="title-input">Title <span class="text-danger">*</span></label>
                            <input type="text" id="title-input" class="form-control" name="title" />
                        </div>
                        <div class="form-group">
                            <label for="description-input">Description <span class="text-danger">*</span></label>
                            <textarea id="description-input" class="form-control" name="description"></textarea>
                        </div>
                        <div class="form-group">
                            <label for="is-active-select">Is Active <span class="text-danger">*</span></label>
                            <select type="text" id="is-active-select" class="form-control" name="is_active">
                                <option value="0">No</option>
                                <option value="1" selected="selected">Yes</option>
                            </select>
                        </div>
                        <input type="hidden" name="csrf_token" value="<?= /* @noEscape */ \Core\Helper\Token::generate(); ?>" />
                        <button type="submit" class="btn btn-primary">Add</button>
                        <a href="<?= $this->makeURL("user/index"); ?>" class="btn btn-link">Cancel</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
