<?php if (count($this->posts)) : ?>
<div class="container">
    <table class="table table-striped">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Title</th>
            <th scope="col">Is Active</th>
            <th scope="col">Created At</th>
            <th scope="col">Updated At</th>
            <th scope="col">Actions</th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($this->posts as $i => $post) : ?>
        <tr>
            <th scope="row"><?= ++$i ?></th>
            <td><a href="<?= $this->makeURL(["post/edit", "?id=" . $post->id]); ?>"><?= $this->escapeHTML($post->title) ?></a></td>
            <td><?= $post->is_active ? "Yes" : "No" ?></td>
            <td><?= $this->escapeHTML($post->created_at) ?></td>
            <td><?= $this->escapeHTML($post->updated_at) ?></td>
            <td><a href="<?= $this->makeURL(['post/delete', "?id=" . $post->id]) ?>">Delete</a></td>
        </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>
<?php endif; ?>